### ISSUE TITLE
vmanage_device_attachment loop through csv file?

### ISSUE THREAD

**Issue by DelmiroCampelo** [CiscoDevNet/python-viptela#160]
I was hoping that you can give me a hand with an issue here. I have about a thousand routers that I’m trying to move from one device template to another. I have all the device specific information on a CSV file that I would like to use for populating all the necessary device fields. I would like to loop through this CSV file, so I don’t have create a playbook with a thousand tasks. I have a playbook that works on a single device basis, but I want to expand it to be able to use for as many routers as I can have on a CSV file. Thank you for any help or tips you can provide. 

```
- hosts: vmanage
  connection: local
  gather_facts: no
  vars:
    ansible_user: testing123
    vmanage_ip: 10.10.2.2
    ansible_password: testing123
    state: present
    host_name_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=1') }}"
    system_ip_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=2') }}"
    site_id_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=3') }}"
    vpn_next_hop_0_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=4') }}"
    vpn_next_hop_1_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=5') }}"
    vpn_if_ipv4_1_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=6') }}"
    vpn_if_ipv4_2_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=7') }}"
    vpn_if_ipv4_var: "{{ lookup('csvfile','123456 file=csvdata.csv delimiter=, col=8') }}"

  tasks:
   - vmanage_device_attachment:
       user: "{{ ansible_user }}"
       host: "{{ vmanage_ip }}"
       password: "{{ ansible_password }}"
       validate_certs: false
       device: Branch2
       template: BRANCHES-CSR-TEMPLATEv2
       variables:
         vpn_next_hop_ip_address_0: "{{ vpn_next_hop_0_var }}"
         vpn_next_hop_ip_address_1: "{{ vpn_next_hop_1_var }}"
         vpn_if_ipv4_address_2: "{{ vpn_if_ipv4_1_var }}"
         vpn_if_ipv4_address: "{{ vpn_if_ipv4_2_var }}"
         host-name: "{{ host_name_var }}"
         system-ip: "{{ system_ip_var }}"
         site-id: "{{ site_id_var }}"
         vpn_if_ipv4_address_1: "{{ vpn_if_ipv4_var }}"
       wait: yes
       state: "{{ state }}"
```

```
root@vm7:/etc/ansible# cat /etc/ansible/python-viptela/ansible/vars/csvdata.csv
system-uuid,hostname,system-ip,site-id,vpn_next_hop_ip_address_0,vpn_next_hop_ip_address_1,vpn_if_ipv4_address_2,vpn_if_ipv4_address,vpn_if_ipv4_address_1
123456,Branch2,100.1.4.1,141,98.1.9.2, 98.1.10.2,98.1.9.1/30,98.1.10.1/30,10.141.0.254/24
```

**Comment by jasonking3** [comment]
Did you look at how we did it in the sdwan-devops repo?  I would just put it all in a YAML file or set of YAML files in an Ansible inventory directory. Then check into version control GitHub, GitLab, etc.

**Comment by DelmiroCampelo** [comment]
Hi @jasonking3 and everyone that helps here. I was able to do what I needed to do using code below. Using a CSV file to populate the variables fields is easier for me. Thank you again for your help and response as always.

```
@vm7:/etc/ansible# cat ./playbooks/vmanage-test23.yml 
- hosts: vmanage
  connection: local
  gather_facts: no
  vars:
    ansible_user: typesomething
    vmanage_ip: 10.10.2.2
    ansible_password: typesomething
    state: present
    
  tasks:
   - name: read csv file
     community.general.read_csv:
       path: '/etc/ansible/files/vmanage_test23.csv' 
     register: vmanage_data
     
   - vmanage_device_attachment:
       user: "{{ ansible_user }}"
       host: "{{ vmanage_ip }}"
       password: "{{ ansible_password }}"
       validate_certs: false
       device: "{{ item.hostname }}"
       template: BRANCHES-CSR-TEMPLATE
       variables:
         vpn_next_hop_ip_address_0: "{{ item['vpn_next_hop_ip_address_0'] }}"
         vpn_next_hop_ip_address_1: "{{ item['vpn_next_hop_ip_address_1'] }}"
         vpn_if_ipv4_address_2: "{{ item['vpn_if_ipv4_address_2'] }}"
         vpn_if_ipv4_address: "{{ item['vpn_if_ipv4_address'] }}"
         host-name: "{{ item.hostname }}"
         system-ip: "{{ item['system-ip'] }}"
         site-id: "{{ item['site-id'] }}"
         vpn_if_ipv4_address_1: "{{ item['vpn_if_ipv4_address_1'] }}"
       wait: yes
       state: "{{ state }}"
     with_items: "{{ vmanage_data.list }}"
```
```
@vm7:/etc/ansible# cat ./files/vmanage_test23.csv 
hostname,system-ip,site-id,vpn_next_hop_ip_address_0,vpn_next_hop_ip_address_1,vpn_if_ipv4_address_2,vpn_if_ipv4_address,vpn_if_ipv4_address_1
Branch2,100.1.4.1,141,98.1.9.2,98.1.10.2,98.1.9.1/30,98.1.10.1/30,10.141.0.254/24
Branch3,100.1.6.1,161,98.1.11.2,98.1.12.2,98.1.12.1/30,98.1.11.1/30,10.161.0.254/24
```
