### ISSUE TITLE
attach device(s) with serial number into template. 

### ISSUE THREAD

**Issue by pm7625** [CiscoDevNet/python-viptela#73]
Hello, would be great to build option which will allow to attach serial number(s), to specific template which exists in vManage. 
Something like vmanage attach device-serial <serial-num> template <template-name> variables <.json>

**Comment by suchandanreddy** [comment]
@pm7625 , please follow the below steps for attaching templates to specific devices with host-name. I have added the filter based on the host-names instead of serial number because providing host-names would be easy from the usability standpoint of view rather than serial numbers. 

pip3 command to have the latest code related to attaching templates to devices:

pip3 install --upgrade git+https://github.com/CiscoDevNet/python-viptela.git@issue-76

Command to attach all the devices and template mapping in the input file `devnet-sandbox-variables.yaml`

`vmanage import attachments -f devnet-sandbox-variables.yaml`

Command to attach selected host-names viz. `site2-cedge01` and `site3-cedge01` to the template mapping in the input file `devnet-sandbox-variables.yaml`

`vmanage import attachments -f devnet-sandbox-variables.yaml -n site2-cedge01 -n site3-cedge01`

Contents of `devnet-sandbox-variables.yaml` are as below. 

yaml file can contain the variables for devices related to same template or different templates

```
vmanage_attachments:
-   host_name: site1-cedge01
    device_type: vedge
    uuid: CSR-807E37A3-537A-07BA-BD71-8FB76DE9DC38
    system_ip: 10.10.1.1
    site_id: '1001'
    template: Site_1_and_2_cEdge_Template
    variables:
        vpn_1_if_name: GigabitEthernet3
        vpn_1_if_description: port.site1-sw01
        vpn_1_if_ipv4_address: 10.10.21.1/24
        vpn_512_next_hop_ip_address: 10.10.20.254
        vpn_512_if_name: GigabitEthernet1
        vpn_512_if_description: port.sbx-mgmt
        vpn_512_if_ipv4_address: 10.10.20.174/24
        vpn_0_next_hop_ip_address: 10.10.23.9
        public_internet_vpn_0_next_hop_ip_address: 10.10.23.41
        internet_vpn_0_if_name: GigabitEthernet4
        internet_vpn_0_if_description: internet-link
        internet_vpn_0_if_ipv4_address: 10.10.23.42/30
        vpn_0_if_name: GigabitEthernet2
        vpn_0_if_description: GigabitEthernet5.wan-rtr01
        vpn_0_if_ipv4_address: 10.10.23.10/30
        system_host_name: site1-cedge01
        system_latitude: '35.852'
        system_longitude: '-78.869'
        system_system_ip: 10.10.1.13
        system_site_id: '1001'
-   host_name: site2-cedge01
    device_type: vedge
    uuid: CSR-DE6DAB19-BA1A-E543-959C-FD117F4A6205
    system_ip: 10.10.1.15
    site_id: '1002'
    template: Site_1_and_2_cEdge_Template
    variables:
        vpn_1_if_name: GigabitEthernet3
        vpn_1_if_description: port.site2-sw01
        vpn_1_if_ipv4_address: 10.10.22.1/24
        vpn_512_next_hop_ip_address: 10.10.20.254
        vpn_512_if_name: GigabitEthernet1
        vpn_512_if_description: port.sbx-mgmt
        vpn_512_if_ipv4_address: 10.10.20.175/24
        vpn_0_next_hop_ip_address: 10.10.23.13
        public_internet_vpn_0_next_hop_ip_address: 10.10.23.45
        internet_vpn_0_if_name: GigabitEthernet4
        internet_vpn_0_if_description: internet-link
        internet_vpn_0_if_ipv4_address: 10.10.23.46/30
        vpn_0_if_name: GigabitEthernet2
        vpn_0_if_description: GigabitEthernet4.wan-rtr01
        vpn_0_if_ipv4_address: 10.10.23.14/30
        system_host_name: site2-cedge01
        system_latitude: '53.277'
        system_longitude: '-8.932'
        system_system_ip: 10.10.1.15
        system_site_id: '1002'
-   host_name: site3-cedge01
    device_type: vedge
    uuid: CSR-E9C755D4-B5B6-8851-F428-3BE65BF0FC45
    system_ip: 10.10.1.18
    site_id: '1010'
    template: Site_1_and_2_cEdge_Template-Copy
    variables:
        vpn_1_if_name: GigabitEthernet3
        vpn_1_if_description: port.site2-sw01
        vpn_1_if_ipv4_address: 10.10.24.1/24
        vpn_512_next_hop_ip_address: 10.10.24.254
        vpn_512_if_name: GigabitEthernet1
        vpn_512_if_description: port.sbx-mgmt
        vpn_512_if_ipv4_address: 10.10.24.175/24
        vpn_0_next_hop_ip_address: 10.10.24.13
        public_internet_vpn_0_next_hop_ip_address: 10.10.24.45
        internet_vpn_0_if_name: GigabitEthernet4
        internet_vpn_0_if_description: internet-link
        internet_vpn_0_if_ipv4_address: 10.10.24.46/30
        vpn_0_if_name: GigabitEthernet2
        vpn_0_if_description: GigabitEthernet4.wan-rtr01
        vpn_0_if_ipv4_address: 10.10.24.14/30
        system_host_name: site3-cedge01
        system_latitude: '56.274'
        system_longitude: '-8.932'
        system_system_ip: 10.10.1.18
        system_site_id: '1010'
-   host_name: site3-vedge01-old
    device_type: vedge
    uuid: 0140a336-5fd5-9829-10d2-f6ba0b177efd
    system_ip: 10.10.1.17
    site_id: '1003'
    template: Site-3-vEdge-CLI-Template
    variables:
        host-name: site3-vedge01-old
        gps-latitude: '52.408'
        gps-longitude: '-2.228'
        System-ip: 10.10.1.17
        Site-id: '1003'
        baud-rate: '9600'
        mpls-interface-ip-address: 10.10.23.18/30
        public-internet-interface-ip-address: 10.10.23.50/30
        mpls-next-hop-ip: 10.10.23.17
        public-internet-next-hop-ip: 10.10.23.49
```
